# Generated by Django 5.2.12 on 2026-04-02 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('nipc', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('morada', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['nipc'],
                'indexes': [models.Index(fields=['nipc'], name='livros_edit_nipc_594407_idx'), models.Index(fields=['nome'], name='livros_edit_nome_563776_idx')],
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('idioma', models.CharField(max_length=3)),
                ('tipo', models.CharField(max_length=50)),
                ('tema', models.CharField(max_length=100)),
                ('data_pub', models.DateField()),
                ('original', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('S', 'Sugerido'), ('D', 'Disponível'), ('E', 'Emprestado'), ('R', 'Reservado'), ('O', 'Retirado')], default='D', max_length=1)),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='livros.editora')),
            ],
            options={
                'ordering': ['titulo'],
                'indexes': [models.Index(fields=['titulo'], name='livros_livr_titulo_f6efa9_idx'), models.Index(fields=['tipo'], name='livros_livr_tipo_77f1a4_idx'), models.Index(fields=['tema'], name='livros_livr_tema_228879_idx')],
            },
        ),
    ]
