# Generated by Django 5.2.12 on 2026-05-01 10:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='data_add',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
